language: go

# Only the last two Go releases are supported by the Go team with security
# updates. Any versions older than that should be considered deprecated.
# Don't bother testing with them. tip builds your code with the latest
# development version of Go. This can warn you that your code will break
# in the next version of Go. Don't worry! Later we declare that test runs
# are allowed to fail on Go tip.
go:
  - "1.10"

jobs:
  include:
  - stage: install
  install:
    - go get -t ./...
  - stage: unit tests
  script:
    - go vet ./... 
    - go test -v ./... -cover -coverprofile=coverage.txt -covermode=atomic
  after_success:
    - bash <(curl -s https://codecov.io/bash)
  - stage: deploy
  deploy:
    provider: heroku
    api_key:
      secure: 05431c6d-2ca7-4f9d-9cf8-6e2bc75c9f24
    app: wemper
    on:
      repo: jasosa/wemper
