language: go
go:
- '1.10'
install:
- go get -t ./...
script:
- go vet ./...
- go test -v ./... -cover -coverprofile=coverage.txt -covermode=atomic
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  api_key:
    secure: TrIq1kWBdhlg5TQ1MUGrxchkWFMyCSxfULrMonCVEM0Lxv1xuyPzVd9ZMpsKcdPYCtXCI3tKlBJ6AXBt6UDNYdNQp4SSW2NC77mcrcw6vv4/sdPmyVZhtAv7lHFhtkxuWw8yyPsT57Uy+Q/rFxnkryNSoGGUa0sQFuoa+KA4t8lmqosJ7xVL/nQlNPh5QeB6DgrOU0Kh+sgIRwY5TAIETGxw1IzmKPHuaI5V73kEpCCohjhdGektSD+g/0luBQvF02QnklFri71BkUO1nhPpRNdPJb/2dU25HoS8JJ73xyC6ph3ylgq9dKyAetUmZ1CixcyHSVSCGOHXYmUuxQfPSBWjPIAbLBAg7lRXgWPJf8RXe67h0UIU4lo0FU/RkX6BGhtkE8+gm0FcXVt2DV4NKAJGnYEeXUuBWH2bh5UC5yhXRzx0CElSZ94OPra/iPxDoXXtsYi3Vihd3Nk8psIVmATHfXVF9Hnk+VqEO1cyxnLQkVPlizzrImZHN8/GZ5u6XnTtuWqokx7ZiyFxuYduKkDqzVVtm2wma5qkOpKYQYbMf9zMNk9QgR+QJZOKTw2lSGLngtd4BGV0WRi46pTIcCDyEop1+UvNWk2wg248SOfX+HDpl6WE7QKjyD7Gzh7AhrYzA1IuPc4Z83mewJiY32IQG/P+Lwui2L1kkkJBhRQ=
  app: wemper
  on:
    repo: jasosa/wemper
